spring:
  application:
    name: clinic-management-system
  data:
    mongodb:
      host: localhost
      port: 27017
      database: clinic_db
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080
  server:
    error:
      whitelabel:
        enabled: false
      path: /error