spring:
  application:
    name: clinic-management-system
  data:
    mongodb:
      uri: mongodb://localhost:27017/clinic_db
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080